before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: cSIsF/M7bFiJ7o6XzRMlIwSwnEBouvZ/TrpZ+3PYGqYVesILW8Hrj9g3E9R7AXD3WfztUIIBTpHjE5BmYkfxICAH4pDtnd3F5udh/Qkowg2hAfGlMZ8CXodBpPK4kRMxYthleg/JbCeBeoY7W7ETs6y3ayMWYqhRCa2tRoU7Oh2s3hOCyDzG3j26qy82BLVR18X52JH50oKqz0DUkIr4iKsWQyV6EGueEMizSnczxx32lJnUekP9EngY/HZ35Qd0e1x6NCp3NZgHLS9x5y+N/4bxbJtc31Xv1jJgot06mFQVPgyFFk1AyOaNZhTWiVpma/MpVJ6CKExvIkZ2g7rz0mkywTHNcJR0vgzh0nCcDiPZDcXKr9p1pkXAzZN2BN25UizB5X2tzjKb6sagQ73t10yyjM4nVQdvih1qoWaxmC5JeBMslPqdi1deg6lCELyGQUS5NI+W9gxDrWG6XwcOkgDkOcFyjMBAvbK6FIG17N83arXMQRmbQHZZL4RDNM20uTHr5ffqS9bN8T+HsDjjqwllc/iXMsFu93jXra77ie/mnc5SMMeM7UZkPZxaWuMclEpolu0q+5fk8pLSHB0Terui+Mlr7gZ5+H5FyV8R2F35tvQRi6Kie3eAhV3/pGvxyrtrGGJtRYnriqWHQY9TqPAplBLkezejC3H6gzlWNxc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
